name: Reusable Workflow
on:
  workflow_call:
    inputs:
      name:
        description: 'Enter the name'
        required: true
        type: string
        default: 'George John'
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Hi ${{ inputs.name }}!, Welcome to the reusable workflow!"